module.exports = class Data1693404184206 {
    name = 'Data1693404184206'

    async up(db) {
        await db.query(`ALTER TABLE "auction_whitelisted_member" DROP CONSTRAINT "FK_aad797677bc7c7c7dc1f1d397f5"`)
        await db.query(`ALTER TABLE "encryption_artifacts" DROP CONSTRAINT "FK_ec8f68a544aadc4fbdadefe4a0a"`)
        await db.query(`ALTER TABLE "session_encryption_artifacts" DROP CONSTRAINT "FK_3612880efd8926a17eba5ab0e1a"`)
        await db.query(`ALTER TABLE "bid" ALTER COLUMN "id" SET NOT NULL`)
        await db.query(`ALTER TABLE "bid" ADD CONSTRAINT "PK_ed405dda320051aca2dcb1a50bb" PRIMARY KEY ("id")`)
        await db.query(`ALTER TABLE "bid" ALTER COLUMN "created_at" SET NOT NULL`)
        await db.query(`ALTER TABLE "bid" ALTER COLUMN "amount" SET NOT NULL`)
        await db.query(`ALTER TABLE "bid" ALTER COLUMN "is_canceled" SET NOT NULL`)
        await db.query(`ALTER TABLE "bid" ALTER COLUMN "created_in_block" SET NOT NULL`)
        await db.query(`ALTER TABLE "bid" ALTER COLUMN "index_in_block" SET NOT NULL`)
        await db.query(`ALTER TABLE "auction" ALTER COLUMN "id" SET NOT NULL`)
        await db.query(`ALTER TABLE "auction" ADD CONSTRAINT "PK_9dc876c629273e71646cf6dfa67" PRIMARY KEY ("id")`)
        await db.query(`ALTER TABLE "auction" ALTER COLUMN "starting_price" SET NOT NULL`)
        await db.query(`ALTER TABLE "auction" ALTER COLUMN "auction_type" SET NOT NULL`)
        await db.query(`ALTER TABLE "auction" ALTER COLUMN "starts_at_block" SET NOT NULL`)
        await db.query(`ALTER TABLE "auction" ALTER COLUMN "is_canceled" SET NOT NULL`)
        await db.query(`ALTER TABLE "auction" ALTER COLUMN "is_completed" SET NOT NULL`)
        await db.query(`ALTER TABLE "banned_member" ALTER COLUMN "id" SET NOT NULL`)
        await db.query(`ALTER TABLE "banned_member" ADD CONSTRAINT "PK_ebdf9a9c6d88f1116a5f2d0815d" PRIMARY KEY ("id")`)
        await db.query(`ALTER TABLE "storage_data_object" ALTER COLUMN "id" SET NOT NULL`)
        await db.query(`ALTER TABLE "storage_data_object" ADD CONSTRAINT "PK_61f224a4aef08f580a5ab4aadf0" PRIMARY KEY ("id")`)
        await db.query(`ALTER TABLE "storage_data_object" ALTER COLUMN "created_at" SET NOT NULL`)
        await db.query(`ALTER TABLE "storage_data_object" ALTER COLUMN "is_accepted" SET NOT NULL`)
        await db.query(`ALTER TABLE "storage_data_object" ALTER COLUMN "size" SET NOT NULL`)
        await db.query(`ALTER TABLE "storage_data_object" ALTER COLUMN "ipfs_hash" SET NOT NULL`)
        await db.query(`ALTER TABLE "storage_data_object" ALTER COLUMN "state_bloat_bond" SET NOT NULL`)
        await db.query(`ALTER TABLE "storage_data_object" ALTER COLUMN "resolved_urls" SET NOT NULL`)
        await db.query(`ALTER TABLE "channel" ALTER COLUMN "id" SET NOT NULL`)
        await db.query(`ALTER TABLE "channel" ADD CONSTRAINT "PK_590f33ee6ee7d76437acf362e39" PRIMARY KEY ("id")`)
        await db.query(`ALTER TABLE "channel" ALTER COLUMN "created_at" SET NOT NULL`)
        await db.query(`ALTER TABLE "channel" ALTER COLUMN "is_censored" SET NOT NULL`)
        await db.query(`ALTER TABLE "channel" ALTER COLUMN "is_excluded" SET NOT NULL`)
        await db.query(`ALTER TABLE "channel" ALTER COLUMN "created_in_block" SET NOT NULL`)
        await db.query(`ALTER TABLE "channel" ALTER COLUMN "reward_account" SET NOT NULL`)
        await db.query(`ALTER TABLE "channel" ALTER COLUMN "channel_state_bloat_bond" SET NOT NULL`)
        await db.query(`ALTER TABLE "channel" ALTER COLUMN "follows_num" SET NOT NULL`)
        await db.query(`ALTER TABLE "channel" ALTER COLUMN "video_views_num" SET NOT NULL`)
        await db.query(`ALTER TABLE "channel" ALTER COLUMN "total_videos_created" SET NOT NULL`)
        await db.query(`ALTER TABLE "video_featured_in_category" ALTER COLUMN "id" SET NOT NULL`)
        await db.query(`ALTER TABLE "video_featured_in_category" ADD CONSTRAINT "PK_f84d38b5cdb7567ac04d6e9d209" PRIMARY KEY ("id")`)
        await db.query(`ALTER TABLE "video_category" ALTER COLUMN "id" SET NOT NULL`)
        await db.query(`ALTER TABLE "video_category" ADD CONSTRAINT "PK_2a5c61f32e9636ee10821e9a58d" PRIMARY KEY ("id")`)
        await db.query(`ALTER TABLE "video_category" ALTER COLUMN "is_supported" SET NOT NULL`)
        await db.query(`ALTER TABLE "video_category" ALTER COLUMN "created_in_block" SET NOT NULL`)
        await db.query(`ALTER TABLE "license" ALTER COLUMN "id" SET NOT NULL`)
        await db.query(`ALTER TABLE "license" ADD CONSTRAINT "PK_f168ac1ca5ba87286d03b2ef905" PRIMARY KEY ("id")`)
        await db.query(`ALTER TABLE "video_subtitle" ALTER COLUMN "id" SET NOT NULL`)
        await db.query(`ALTER TABLE "video_subtitle" ADD CONSTRAINT "PK_2ac3e585fc608e673e7fbf94d8e" PRIMARY KEY ("id")`)
        await db.query(`ALTER TABLE "video_subtitle" ALTER COLUMN "type" SET NOT NULL`)
        await db.query(`ALTER TABLE "video_subtitle" ALTER COLUMN "mime_type" SET NOT NULL`)
        await db.query(`ALTER TABLE "comment_reaction" ALTER COLUMN "id" SET NOT NULL`)
        await db.query(`ALTER TABLE "comment_reaction" ADD CONSTRAINT "PK_87f27d282c06eb61b1e0cde2d24" PRIMARY KEY ("id")`)
        await db.query(`ALTER TABLE "comment_reaction" ALTER COLUMN "reaction_id" SET NOT NULL`)
        await db.query(`ALTER TABLE "comment" ALTER COLUMN "id" SET NOT NULL`)
        await db.query(`ALTER TABLE "comment" ADD CONSTRAINT "PK_0b0e4bbc8415ec426f87f3a88e2" PRIMARY KEY ("id")`)
        await db.query(`ALTER TABLE "comment" ALTER COLUMN "created_at" SET NOT NULL`)
        await db.query(`ALTER TABLE "comment" ALTER COLUMN "text" SET NOT NULL`)
        await db.query(`ALTER TABLE "comment" ALTER COLUMN "status" SET NOT NULL`)
        await db.query(`ALTER TABLE "comment" ALTER COLUMN "replies_count" SET NOT NULL`)
        await db.query(`ALTER TABLE "comment" ALTER COLUMN "reactions_count" SET NOT NULL`)
        await db.query(`ALTER TABLE "comment" ALTER COLUMN "reactions_and_replies_count" SET NOT NULL`)
        await db.query(`ALTER TABLE "comment" ALTER COLUMN "is_edited" SET NOT NULL`)
        await db.query(`ALTER TABLE "comment" ALTER COLUMN "is_excluded" SET NOT NULL`)
        await db.query(`ALTER TABLE "video_reaction" ALTER COLUMN "id" SET NOT NULL`)
        await db.query(`ALTER TABLE "video_reaction" ADD CONSTRAINT "PK_504876585c394f4ab33665dd44b" PRIMARY KEY ("id")`)
        await db.query(`ALTER TABLE "video_reaction" ALTER COLUMN "created_at" SET NOT NULL`)
        await db.query(`ALTER TABLE "video_reaction" ALTER COLUMN "reaction" SET NOT NULL`)
        await db.query(`ALTER TABLE "video" ALTER COLUMN "id" SET NOT NULL`)
        await db.query(`ALTER TABLE "video" ADD CONSTRAINT "PK_1a2f3856250765d72e7e1636c8e" PRIMARY KEY ("id")`)
        await db.query(`ALTER TABLE "video" ALTER COLUMN "created_at" SET NOT NULL`)
        await db.query(`ALTER TABLE "video" ALTER COLUMN "is_censored" SET NOT NULL`)
        await db.query(`ALTER TABLE "video" ALTER COLUMN "is_excluded" SET NOT NULL`)
        await db.query(`ALTER TABLE "video" ALTER COLUMN "video_state_bloat_bond" SET NOT NULL`)
        await db.query(`ALTER TABLE "video" ALTER COLUMN "created_in_block" SET NOT NULL`)
        await db.query(`ALTER TABLE "video" ALTER COLUMN "is_comment_section_enabled" SET NOT NULL`)
        await db.query(`ALTER TABLE "video" ALTER COLUMN "comments_count" SET NOT NULL`)
        await db.query(`ALTER TABLE "video" ALTER COLUMN "is_reaction_feature_enabled" SET NOT NULL`)
        await db.query(`ALTER TABLE "video" ALTER COLUMN "reactions_count" SET NOT NULL`)
        await db.query(`ALTER TABLE "video" ALTER COLUMN "views_num" SET NOT NULL`)
        await db.query(`ALTER TABLE "video" ALTER COLUMN "video_relevance" SET NOT NULL`)
        await db.query(`ALTER TABLE "owned_nft" ALTER COLUMN "id" SET NOT NULL`)
        await db.query(`ALTER TABLE "owned_nft" ADD CONSTRAINT "PK_5e0c289b350e863668fff44bb56" PRIMARY KEY ("id")`)
        await db.query(`ALTER TABLE "owned_nft" ALTER COLUMN "created_at" SET NOT NULL`)
        await db.query(`ALTER TABLE "owned_nft" ALTER COLUMN "video_id" SET NOT NULL`)
        await db.query(`ALTER TABLE "owned_nft" ADD CONSTRAINT "UQ_466896e39b9ec953f4f2545622d" UNIQUE ("video_id")`)
        await db.query(`ALTER TABLE "owned_nft" ALTER COLUMN "owner" SET NOT NULL`)
        await db.query(`ALTER TABLE "owned_nft" ALTER COLUMN "is_featured" SET NOT NULL`)
        await db.query(`ALTER TABLE "channel_follow" ALTER COLUMN "id" SET NOT NULL`)
        await db.query(`ALTER TABLE "channel_follow" ADD CONSTRAINT "PK_9410df2b9a316af3f0d216f9487" PRIMARY KEY ("id")`)
        await db.query(`ALTER TABLE "channel_follow" ALTER COLUMN "channel_id" SET NOT NULL`)
        await db.query(`ALTER TABLE "channel_follow" ALTER COLUMN "timestamp" SET NOT NULL`)
        await db.query(`ALTER TABLE "video_view_event" ALTER COLUMN "id" SET NOT NULL`)
        await db.query(`ALTER TABLE "video_view_event" ADD CONSTRAINT "PK_2efd85597a6a7a704fc4d0f7701" PRIMARY KEY ("id")`)
        await db.query(`ALTER TABLE "video_view_event" ALTER COLUMN "video_id" SET NOT NULL`)
        await db.query(`ALTER TABLE "video_view_event" ALTER COLUMN "timestamp" SET NOT NULL`)
        await db.query(`ALTER TABLE "report" ALTER COLUMN "id" SET NOT NULL`)
        await db.query(`ALTER TABLE "report" ADD CONSTRAINT "PK_99e4d0bea58cba73c57f935a546" PRIMARY KEY ("id")`)
        await db.query(`ALTER TABLE "report" ALTER COLUMN "timestamp" SET NOT NULL`)
        await db.query(`ALTER TABLE "report" ALTER COLUMN "rationale" SET NOT NULL`)
        await db.query(`ALTER TABLE "nft_featuring_request" ALTER COLUMN "id" SET NOT NULL`)
        await db.query(`ALTER TABLE "nft_featuring_request" ADD CONSTRAINT "PK_d0b1ccb74336b30b9575387d328" PRIMARY KEY ("id")`)
        await db.query(`ALTER TABLE "nft_featuring_request" ALTER COLUMN "nft_id" SET NOT NULL`)
        await db.query(`ALTER TABLE "nft_featuring_request" ALTER COLUMN "timestamp" SET NOT NULL`)
        await db.query(`ALTER TABLE "nft_featuring_request" ALTER COLUMN "rationale" SET NOT NULL`)
        await db.query(`ALTER TABLE "user" ALTER COLUMN "id" SET NOT NULL`)
        await db.query(`ALTER TABLE "user" ADD CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id")`)
        await db.query(`ALTER TABLE "user" ALTER COLUMN "is_root" SET NOT NULL`)
        await db.query(`ALTER TABLE "account" ALTER COLUMN "id" SET NOT NULL`)
        await db.query(`ALTER TABLE "account" ADD CONSTRAINT "PK_54115ee388cdb6d86bb4bf5b2ea" PRIMARY KEY ("id")`)
        await db.query(`ALTER TABLE "account" ALTER COLUMN "user_id" SET NOT NULL`)
        await db.query(`ALTER TABLE "account" ADD CONSTRAINT "UQ_efef1e5fdbe318a379c06678c51" UNIQUE ("user_id")`)
        await db.query(`ALTER TABLE "account" ALTER COLUMN "email" SET NOT NULL`)
        await db.query(`ALTER TABLE "account" ADD CONSTRAINT "UQ_4c8f96ccf523e9a3faefd5bdd4c" UNIQUE ("email")`)
        await db.query(`ALTER TABLE "account" ALTER COLUMN "is_email_confirmed" SET NOT NULL`)
        await db.query(`ALTER TABLE "account" ALTER COLUMN "is_blocked" SET NOT NULL`)
        await db.query(`ALTER TABLE "account" ALTER COLUMN "registered_at" SET NOT NULL`)
        await db.query(`ALTER TABLE "account" ALTER COLUMN "membership_id" SET NOT NULL`)
        await db.query(`ALTER TABLE "account" ADD CONSTRAINT "UQ_601b93655bcbe73cb58d8c80cd3" UNIQUE ("membership_id")`)
        await db.query(`ALTER TABLE "account" ALTER COLUMN "joystream_account" SET NOT NULL`)
        await db.query(`ALTER TABLE "account" ADD CONSTRAINT "UQ_df4da05a7a80c1afd18b8f09900" UNIQUE ("joystream_account")`)
        await db.query(`ALTER TABLE "session" ALTER COLUMN "id" SET NOT NULL`)
        await db.query(`ALTER TABLE "session" ADD CONSTRAINT "PK_f55da76ac1c3ac420f444d2ff11" PRIMARY KEY ("id")`)
        await db.query(`ALTER TABLE "session" ALTER COLUMN "browser" SET NOT NULL`)
        await db.query(`ALTER TABLE "session" ALTER COLUMN "os" SET NOT NULL`)
        await db.query(`ALTER TABLE "session" ALTER COLUMN "device" SET NOT NULL`)
        await db.query(`ALTER TABLE "session" ALTER COLUMN "ip" SET NOT NULL`)
        await db.query(`ALTER TABLE "session" ALTER COLUMN "started_at" SET NOT NULL`)
        await db.query(`ALTER TABLE "session" ALTER COLUMN "expiry" SET NOT NULL`)
        await db.query(`ALTER TABLE "token" ALTER COLUMN "id" SET NOT NULL`)
        await db.query(`ALTER TABLE "token" ADD CONSTRAINT "PK_82fae97f905930df5d62a702fc9" PRIMARY KEY ("id")`)
        await db.query(`ALTER TABLE "token" ALTER COLUMN "type" SET NOT NULL`)
        await db.query(`ALTER TABLE "token" ALTER COLUMN "issued_at" SET NOT NULL`)
        await db.query(`ALTER TABLE "token" ALTER COLUMN "expiry" SET NOT NULL`)
        await db.query(`ALTER TABLE "event" ALTER COLUMN "id" SET NOT NULL`)
        await db.query(`ALTER TABLE "event" ADD CONSTRAINT "PK_30c2f3bbaf6d34a55f8ae6e4614" PRIMARY KEY ("id")`)
        await db.query(`ALTER TABLE "event" ALTER COLUMN "in_block" SET NOT NULL`)
        await db.query(`ALTER TABLE "event" ALTER COLUMN "index_in_block" SET NOT NULL`)
        await db.query(`ALTER TABLE "event" ALTER COLUMN "timestamp" SET NOT NULL`)
        await db.query(`ALTER TABLE "event" ALTER COLUMN "data" SET NOT NULL`)
        await db.query(`ALTER TABLE "notification" ALTER COLUMN "id" SET NOT NULL`)
        await db.query(`ALTER TABLE "notification" ADD CONSTRAINT "PK_705b6c7cdf9b2c2ff7ac7872cb7" PRIMARY KEY ("id")`)
        await db.query(`ALTER TABLE "nft_history_entry" ALTER COLUMN "id" SET NOT NULL`)
        await db.query(`ALTER TABLE "nft_history_entry" ADD CONSTRAINT "PK_9018e80b335a965a54959c4c6e2" PRIMARY KEY ("id")`)
        await db.query(`ALTER TABLE "nft_activity" ALTER COLUMN "id" SET NOT NULL`)
        await db.query(`ALTER TABLE "nft_activity" ADD CONSTRAINT "PK_1553b1bbf8000039875a6e31536" PRIMARY KEY ("id")`)
        await db.query(`ALTER TABLE "gateway_config" ALTER COLUMN "id" SET NOT NULL`)
        await db.query(`ALTER TABLE "gateway_config" ADD CONSTRAINT "PK_db1fa5a857fb6292eee4c493e6f" PRIMARY KEY ("id")`)
        await db.query(`ALTER TABLE "gateway_config" ALTER COLUMN "value" SET NOT NULL`)
        await db.query(`ALTER TABLE "gateway_config" ALTER COLUMN "updated_at" SET NOT NULL`)
        await db.query(`ALTER TABLE "video_hero" ALTER COLUMN "id" SET NOT NULL`)
        await db.query(`ALTER TABLE "video_hero" ADD CONSTRAINT "PK_f3b63979879773378afac0b9495" PRIMARY KEY ("id")`)
        await db.query(`ALTER TABLE "video_hero" ALTER COLUMN "hero_title" SET NOT NULL`)
        await db.query(`ALTER TABLE "video_hero" ALTER COLUMN "hero_video_cut_url" SET NOT NULL`)
        await db.query(`ALTER TABLE "video_hero" ALTER COLUMN "hero_poster_url" SET NOT NULL`)
        await db.query(`ALTER TABLE "video_media_encoding" ALTER COLUMN "id" SET NOT NULL`)
        await db.query(`ALTER TABLE "video_media_encoding" ADD CONSTRAINT "PK_52e25874f8d8a381e154d1125e0" PRIMARY KEY ("id")`)
        await db.query(`ALTER TABLE "video_media_metadata" ALTER COLUMN "id" SET NOT NULL`)
        await db.query(`ALTER TABLE "video_media_metadata" ADD CONSTRAINT "PK_86a13815734e589cd86d0465e2d" PRIMARY KEY ("id")`)
        await db.query(`ALTER TABLE "video_media_metadata" ALTER COLUMN "video_id" SET NOT NULL`)
        await db.query(`ALTER TABLE "video_media_metadata" ADD CONSTRAINT "UQ_4dc101240e8e1536b770aee202a" UNIQUE ("video_id")`)
        await db.query(`ALTER TABLE "video_media_metadata" ALTER COLUMN "created_in_block" SET NOT NULL`)
        await db.query(`CREATE INDEX "IDX_9e594e5a61c0f3cb25679f6ba8" ON "bid" ("auction_id") `)
        await db.query(`CREATE INDEX "IDX_3caf2d6b31d2fe45a2b85b8191" ON "bid" ("nft_id") `)
        await db.query(`CREATE INDEX "IDX_e7618559409a903a897164156b" ON "bid" ("bidder_id") `)
        await db.query(`CREATE INDEX "IDX_32cb73025ec49c87f4c594a265" ON "bid" ("previous_top_bid_id") `)
        await db.query(`CREATE INDEX "IDX_cfb47e97e60c9d1462576f85a8" ON "auction" ("nft_id") `)
        await db.query(`CREATE INDEX "IDX_a3127ec87cccc5696b92cac4e0" ON "auction" ("winning_member_id") `)
        await db.query(`CREATE INDEX "IDX_1673ad4b059742fbabfc40b275" ON "auction" ("top_bid_id") `)
        await db.query(`CREATE INDEX "IDX_ed36c6c26bf5410796c2fc21f7" ON "banned_member" ("channel_id") `)
        await db.query(`CREATE INDEX "IDX_f29ff095bdb945975deca021ad" ON "banned_member" ("member_id", "channel_id") `)
        await db.query(`CREATE INDEX "IDX_ff8014300b8039dbaed764f51b" ON "storage_data_object" ("storage_bag_id") `)
        await db.query(`CREATE INDEX "IDX_25c85bc448b5e236a4c1a5f789" ON "channel" ("owner_member_id") `)
        await db.query(`CREATE INDEX "IDX_a77e12f3d8c6ced020e179a5e9" ON "channel" ("cover_photo_id") `)
        await db.query(`CREATE INDEX "IDX_6997e94413b3f2f25a84e4a96f" ON "channel" ("avatar_photo_id") `)
        await db.query(`CREATE INDEX "IDX_e58a2e1d78b8eccf40531a7fdb" ON "channel" ("language") `)
        await db.query(`CREATE INDEX "IDX_118ecfa0199aeb5a014906933e" ON "channel" ("entry_app_id") `)
        await db.query(`CREATE INDEX "IDX_7b16ddad43901921a8d3c8eab7" ON "video_featured_in_category" ("video_id") `)
        await db.query(`CREATE INDEX "IDX_6d0917e1ac0cc06c8075bcf256" ON "video_featured_in_category" ("category_id", "video_id") `)
        await db.query(`CREATE INDEX "IDX_cbe7e5d162a819e4ee2e2f6105" ON "video_category" ("name") `)
        await db.query(`CREATE INDEX "IDX_da26b34f037c0d59d3c0d0646e" ON "video_category" ("parent_category_id") `)
        await db.query(`CREATE INDEX "IDX_2203674f18d8052ed6bac39625" ON "video_subtitle" ("video_id") `)
        await db.query(`CREATE INDEX "IDX_ffa63c28188eecc32af921bfc3" ON "video_subtitle" ("language") `)
        await db.query(`CREATE INDEX "IDX_b6eabfb8de4128b28d73681020" ON "video_subtitle" ("asset_id") `)
        await db.query(`CREATE INDEX "IDX_15080d9fb7cf8b563103dd9d90" ON "comment_reaction" ("member_id") `)
        await db.query(`CREATE INDEX "IDX_962582f04d3f639e33f43c54bb" ON "comment_reaction" ("comment_id") `)
        await db.query(`CREATE INDEX "IDX_d7995b1d57614a6fbd0c103874" ON "comment_reaction" ("video_id") `)
        await db.query(`CREATE INDEX "IDX_3ce66469b26697baa097f8da92" ON "comment" ("author_id") `)
        await db.query(`CREATE INDEX "IDX_1ff03403fd31dfeaba0623a89c" ON "comment" ("video_id") `)
        await db.query(`CREATE INDEX "IDX_c3c2abe750c76c7c8e305f71f2" ON "comment" ("status") `)
        await db.query(`CREATE INDEX "IDX_ac69bddf8202b7c0752d9dc8f3" ON "comment" ("parent_comment_id") `)
        await db.query(`CREATE INDEX "IDX_73dda64f53bbc7ec7035d5e7f0" ON "video_reaction" ("member_id") `)
        await db.query(`CREATE INDEX "IDX_436a3836eb47acb5e1e3c88dde" ON "video_reaction" ("video_id") `)
        await db.query(`CREATE INDEX "IDX_81b11ef99a9db9ef1aed040d75" ON "video" ("channel_id") `)
        await db.query(`CREATE INDEX "IDX_2a5c61f32e9636ee10821e9a58" ON "video" ("category_id") `)
        await db.query(`CREATE INDEX "IDX_8530d052cc79b420f7ce2b4e09" ON "video" ("thumbnail_photo_id") `)
        await db.query(`CREATE INDEX "IDX_75fbab42a4cb18371b6d5004b0" ON "video" ("language") `)
        await db.query(`CREATE INDEX "IDX_3ec633ae5d0477f512b4ed957d" ON "video" ("license_id") `)
        await db.query(`CREATE INDEX "IDX_2db879ed42e3308fe65e679672" ON "video" ("media_id") `)
        await db.query(`CREATE INDEX "IDX_54f88a7decf7d22fd9bd9fa439" ON "video" ("pinned_comment_id") `)
        await db.query(`CREATE INDEX "IDX_6c49ad08c44d36d11f77c426e4" ON "video" ("entry_app_id") `)
        await db.query(`CREATE INDEX "IDX_466896e39b9ec953f4f2545622" ON "owned_nft" ("video_id") `)
        await db.query(`CREATE INDEX "IDX_822778b4b1ea8e3b60b127cb8b" ON "channel_follow" ("user_id") `)
        await db.query(`CREATE INDEX "IDX_9bc0651dda94437ec18764a260" ON "channel_follow" ("channel_id") `)
        await db.query(`CREATE INDEX "IDX_2e29fba63e12a2b1818e0782d7" ON "video_view_event" ("video_id") `)
        await db.query(`CREATE INDEX "IDX_31e1e798ec387ad905cf98d33b" ON "video_view_event" ("user_id") `)
        await db.query(`CREATE INDEX "IDX_c6686efa4cd49fa9a429f01bac" ON "report" ("user_id") `)
        await db.query(`CREATE INDEX "IDX_893057921f4b5cc37a0ef36684" ON "report" ("channel_id") `)
        await db.query(`CREATE INDEX "IDX_f732b6f82095a935db68c9491f" ON "report" ("video_id") `)
        await db.query(`CREATE INDEX "IDX_519be2a41216c278c35f254dcb" ON "nft_featuring_request" ("user_id") `)
        await db.query(`CREATE INDEX "IDX_76d87e26cce72ac2e7ffa28dfb" ON "nft_featuring_request" ("nft_id") `)
        await db.query(`CREATE INDEX "IDX_efef1e5fdbe318a379c06678c5" ON "account" ("user_id") `)
        await db.query(`CREATE INDEX "IDX_4c8f96ccf523e9a3faefd5bdd4" ON "account" ("email") `)
        await db.query(`CREATE INDEX "IDX_601b93655bcbe73cb58d8c80cd" ON "account" ("membership_id") `)
        await db.query(`CREATE INDEX "IDX_df4da05a7a80c1afd18b8f0990" ON "account" ("joystream_account") `)
        await db.query(`CREATE INDEX "IDX_30e98e8746699fb9af235410af" ON "session" ("user_id") `)
        await db.query(`CREATE INDEX "IDX_fae5a6b4a57f098e9af8520d49" ON "session" ("account_id") `)
        await db.query(`CREATE INDEX "IDX_213b5a19bfdbe0ab6e06b1dede" ON "session" ("ip") `)
        await db.query(`CREATE INDEX "IDX_a6fe18c105f85a63d761ccb078" ON "token" ("issued_for_id") `)
        await db.query(`CREATE INDEX "IDX_8f3f220c4e717207d841d4e6d4" ON "event" ("in_extrinsic") `)
        await db.query(`CREATE INDEX "IDX_ac8de39626657d3c0e909d9d82" ON "notification" ("member_id") `)
        await db.query(`CREATE INDEX "IDX_122be1f0696e0255acf95f9e33" ON "notification" ("event_id") `)
        await db.query(`CREATE INDEX "IDX_57f51d35ecab042478fe2e31c1" ON "nft_history_entry" ("nft_id") `)
        await db.query(`CREATE INDEX "IDX_d1a28b178f5d028d048d40ce20" ON "nft_history_entry" ("event_id") `)
        await db.query(`CREATE INDEX "IDX_18a65713a9fd0715c7a980f5d5" ON "nft_activity" ("member_id") `)
        await db.query(`CREATE INDEX "IDX_94d325a753f2c08fdd416eb095" ON "nft_activity" ("event_id") `)
        await db.query(`CREATE INDEX "IDX_9feac5d9713a9f07e32eb8ba7a" ON "video_hero" ("video_id") `)
        await db.query(`CREATE INDEX "IDX_5944dc5896cb16bd395414a0ce" ON "video_media_metadata" ("encoding_id") `)
        await db.query(`CREATE INDEX "IDX_4dc101240e8e1536b770aee202" ON "video_media_metadata" ("video_id") `)
        await db.query(`ALTER TABLE "banned_member" ADD CONSTRAINT "BannedMember_member_channel" UNIQUE ("member_id", "channel_id") DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "video_featured_in_category" ADD CONSTRAINT "VideoFeaturedInCategory_category_video" UNIQUE ("category_id", "video_id") DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "bid" ADD CONSTRAINT "FK_9e594e5a61c0f3cb25679f6ba8d" FOREIGN KEY ("auction_id") REFERENCES "auction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "bid" ADD CONSTRAINT "FK_3caf2d6b31d2fe45a2b85b81912" FOREIGN KEY ("nft_id") REFERENCES "owned_nft"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "bid" ADD CONSTRAINT "FK_e7618559409a903a897164156b7" FOREIGN KEY ("bidder_id") REFERENCES "membership"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "bid" ADD CONSTRAINT "FK_32cb73025ec49c87f4c594a265f" FOREIGN KEY ("previous_top_bid_id") REFERENCES "bid"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "auction" ADD CONSTRAINT "FK_cfb47e97e60c9d1462576f85a88" FOREIGN KEY ("nft_id") REFERENCES "owned_nft"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "auction" ADD CONSTRAINT "FK_a3127ec87cccc5696b92cac4e09" FOREIGN KEY ("winning_member_id") REFERENCES "membership"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "auction" ADD CONSTRAINT "FK_1673ad4b059742fbabfc40b275c" FOREIGN KEY ("top_bid_id") REFERENCES "bid"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "auction_whitelisted_member" ADD CONSTRAINT "FK_aad797677bc7c7c7dc1f1d397f5" FOREIGN KEY ("auction_id") REFERENCES "auction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "banned_member" ADD CONSTRAINT "FK_b94ea874da235d9b6fbc35cf58e" FOREIGN KEY ("member_id") REFERENCES "membership"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "banned_member" ADD CONSTRAINT "FK_ed36c6c26bf5410796c2fc21f74" FOREIGN KEY ("channel_id") REFERENCES "channel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "storage_data_object" ADD CONSTRAINT "FK_ff8014300b8039dbaed764f51bc" FOREIGN KEY ("storage_bag_id") REFERENCES "storage_bag"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "channel" ADD CONSTRAINT "FK_25c85bc448b5e236a4c1a5f7895" FOREIGN KEY ("owner_member_id") REFERENCES "membership"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "channel" ADD CONSTRAINT "FK_a77e12f3d8c6ced020e179a5e94" FOREIGN KEY ("cover_photo_id") REFERENCES "storage_data_object"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "channel" ADD CONSTRAINT "FK_6997e94413b3f2f25a84e4a96f8" FOREIGN KEY ("avatar_photo_id") REFERENCES "storage_data_object"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "channel" ADD CONSTRAINT "FK_118ecfa0199aeb5a014906933e8" FOREIGN KEY ("entry_app_id") REFERENCES "app"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "video_featured_in_category" ADD CONSTRAINT "FK_7b16ddad43901921a8d3c8eab71" FOREIGN KEY ("video_id") REFERENCES "video"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "video_featured_in_category" ADD CONSTRAINT "FK_0e6bb49ce9d022cd872f3ab4288" FOREIGN KEY ("category_id") REFERENCES "video_category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "video_category" ADD CONSTRAINT "FK_da26b34f037c0d59d3c0d0646e9" FOREIGN KEY ("parent_category_id") REFERENCES "video_category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "video_subtitle" ADD CONSTRAINT "FK_2203674f18d8052ed6bac396252" FOREIGN KEY ("video_id") REFERENCES "video"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "video_subtitle" ADD CONSTRAINT "FK_b6eabfb8de4128b28d73681020f" FOREIGN KEY ("asset_id") REFERENCES "storage_data_object"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "comment_reaction" ADD CONSTRAINT "FK_15080d9fb7cf8b563103dd9d900" FOREIGN KEY ("member_id") REFERENCES "membership"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "comment_reaction" ADD CONSTRAINT "FK_962582f04d3f639e33f43c54bbc" FOREIGN KEY ("comment_id") REFERENCES "comment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "comment_reaction" ADD CONSTRAINT "FK_d7995b1d57614a6fbd0c103874d" FOREIGN KEY ("video_id") REFERENCES "video"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "comment" ADD CONSTRAINT "FK_3ce66469b26697baa097f8da923" FOREIGN KEY ("author_id") REFERENCES "membership"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "comment" ADD CONSTRAINT "FK_1ff03403fd31dfeaba0623a89cf" FOREIGN KEY ("video_id") REFERENCES "video"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "comment" ADD CONSTRAINT "FK_ac69bddf8202b7c0752d9dc8f32" FOREIGN KEY ("parent_comment_id") REFERENCES "comment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "video_reaction" ADD CONSTRAINT "FK_73dda64f53bbc7ec7035d5e7f09" FOREIGN KEY ("member_id") REFERENCES "membership"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "video_reaction" ADD CONSTRAINT "FK_436a3836eb47acb5e1e3c88ddea" FOREIGN KEY ("video_id") REFERENCES "video"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "video" ADD CONSTRAINT "FK_81b11ef99a9db9ef1aed040d750" FOREIGN KEY ("channel_id") REFERENCES "channel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "video" ADD CONSTRAINT "FK_2a5c61f32e9636ee10821e9a58d" FOREIGN KEY ("category_id") REFERENCES "video_category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "video" ADD CONSTRAINT "FK_8530d052cc79b420f7ce2b4e09d" FOREIGN KEY ("thumbnail_photo_id") REFERENCES "storage_data_object"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "video" ADD CONSTRAINT "FK_3ec633ae5d0477f512b4ed957d6" FOREIGN KEY ("license_id") REFERENCES "license"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "video" ADD CONSTRAINT "FK_2db879ed42e3308fe65e6796729" FOREIGN KEY ("media_id") REFERENCES "storage_data_object"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "video" ADD CONSTRAINT "FK_54f88a7decf7d22fd9bd9fa439a" FOREIGN KEY ("pinned_comment_id") REFERENCES "comment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "video" ADD CONSTRAINT "FK_6c49ad08c44d36d11f77c426e43" FOREIGN KEY ("entry_app_id") REFERENCES "app"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "owned_nft" ADD CONSTRAINT "FK_466896e39b9ec953f4f2545622d" FOREIGN KEY ("video_id") REFERENCES "video"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "channel_follow" ADD CONSTRAINT "FK_822778b4b1ea8e3b60b127cb8b1" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "video_view_event" ADD CONSTRAINT "FK_31e1e798ec387ad905cf98d33b0" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "report" ADD CONSTRAINT "FK_c6686efa4cd49fa9a429f01bac8" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "nft_featuring_request" ADD CONSTRAINT "FK_519be2a41216c278c35f254dcba" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "account" ADD CONSTRAINT "FK_efef1e5fdbe318a379c06678c51" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "account" ADD CONSTRAINT "FK_601b93655bcbe73cb58d8c80cd3" FOREIGN KEY ("membership_id") REFERENCES "membership"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "encryption_artifacts" ADD CONSTRAINT "FK_ec8f68a544aadc4fbdadefe4a0a" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "session" ADD CONSTRAINT "FK_30e98e8746699fb9af235410aff" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "session" ADD CONSTRAINT "FK_fae5a6b4a57f098e9af8520d499" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "session_encryption_artifacts" ADD CONSTRAINT "FK_3612880efd8926a17eba5ab0e1a" FOREIGN KEY ("session_id") REFERENCES "session"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "token" ADD CONSTRAINT "FK_a6fe18c105f85a63d761ccb0780" FOREIGN KEY ("issued_for_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_ac8de39626657d3c0e909d9d82f" FOREIGN KEY ("member_id") REFERENCES "membership"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_122be1f0696e0255acf95f9e336" FOREIGN KEY ("event_id") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "nft_history_entry" ADD CONSTRAINT "FK_57f51d35ecab042478fe2e31c19" FOREIGN KEY ("nft_id") REFERENCES "owned_nft"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "nft_history_entry" ADD CONSTRAINT "FK_d1a28b178f5d028d048d40ce208" FOREIGN KEY ("event_id") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "nft_activity" ADD CONSTRAINT "FK_18a65713a9fd0715c7a980f5d54" FOREIGN KEY ("member_id") REFERENCES "membership"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "nft_activity" ADD CONSTRAINT "FK_94d325a753f2c08fdd416eb095f" FOREIGN KEY ("event_id") REFERENCES "event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "video_hero" ADD CONSTRAINT "FK_9feac5d9713a9f07e32eb8ba7a1" FOREIGN KEY ("video_id") REFERENCES "video"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "video_media_metadata" ADD CONSTRAINT "FK_5944dc5896cb16bd395414a0ce0" FOREIGN KEY ("encoding_id") REFERENCES "video_media_encoding"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "video_media_metadata" ADD CONSTRAINT "FK_4dc101240e8e1536b770aee202a" FOREIGN KEY ("video_id") REFERENCES "video"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
    }

    async down(db) {
        await db.query(`ALTER TABLE "auction_whitelisted_member" ADD CONSTRAINT "FK_aad797677bc7c7c7dc1f1d397f5" FOREIGN KEY ("auction_id") REFERENCES "admin"."auction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "encryption_artifacts" ADD CONSTRAINT "FK_ec8f68a544aadc4fbdadefe4a0a" FOREIGN KEY ("account_id") REFERENCES "admin"."account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "session_encryption_artifacts" ADD CONSTRAINT "FK_3612880efd8926a17eba5ab0e1a" FOREIGN KEY ("session_id") REFERENCES "admin"."session"("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED`)
        await db.query(`ALTER TABLE "bid" ALTER COLUMN "id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "bid" DROP CONSTRAINT "PK_ed405dda320051aca2dcb1a50bb"`)
        await db.query(`ALTER TABLE "bid" ALTER COLUMN "created_at" DROP NOT NULL`)
        await db.query(`ALTER TABLE "bid" ALTER COLUMN "amount" DROP NOT NULL`)
        await db.query(`ALTER TABLE "bid" ALTER COLUMN "is_canceled" DROP NOT NULL`)
        await db.query(`ALTER TABLE "bid" ALTER COLUMN "created_in_block" DROP NOT NULL`)
        await db.query(`ALTER TABLE "bid" ALTER COLUMN "index_in_block" DROP NOT NULL`)
        await db.query(`ALTER TABLE "auction" ALTER COLUMN "id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "auction" DROP CONSTRAINT "PK_9dc876c629273e71646cf6dfa67"`)
        await db.query(`ALTER TABLE "auction" ALTER COLUMN "starting_price" DROP NOT NULL`)
        await db.query(`ALTER TABLE "auction" ALTER COLUMN "auction_type" DROP NOT NULL`)
        await db.query(`ALTER TABLE "auction" ALTER COLUMN "starts_at_block" DROP NOT NULL`)
        await db.query(`ALTER TABLE "auction" ALTER COLUMN "is_canceled" DROP NOT NULL`)
        await db.query(`ALTER TABLE "auction" ALTER COLUMN "is_completed" DROP NOT NULL`)
        await db.query(`ALTER TABLE "banned_member" ALTER COLUMN "id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "banned_member" DROP CONSTRAINT "PK_ebdf9a9c6d88f1116a5f2d0815d"`)
        await db.query(`ALTER TABLE "storage_data_object" ALTER COLUMN "id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "storage_data_object" DROP CONSTRAINT "PK_61f224a4aef08f580a5ab4aadf0"`)
        await db.query(`ALTER TABLE "storage_data_object" ALTER COLUMN "created_at" DROP NOT NULL`)
        await db.query(`ALTER TABLE "storage_data_object" ALTER COLUMN "is_accepted" DROP NOT NULL`)
        await db.query(`ALTER TABLE "storage_data_object" ALTER COLUMN "size" DROP NOT NULL`)
        await db.query(`ALTER TABLE "storage_data_object" ALTER COLUMN "ipfs_hash" DROP NOT NULL`)
        await db.query(`ALTER TABLE "storage_data_object" ALTER COLUMN "state_bloat_bond" DROP NOT NULL`)
        await db.query(`ALTER TABLE "storage_data_object" ALTER COLUMN "resolved_urls" DROP NOT NULL`)
        await db.query(`ALTER TABLE "channel" ALTER COLUMN "id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "channel" DROP CONSTRAINT "PK_590f33ee6ee7d76437acf362e39"`)
        await db.query(`ALTER TABLE "channel" ALTER COLUMN "created_at" DROP NOT NULL`)
        await db.query(`ALTER TABLE "channel" ALTER COLUMN "is_censored" DROP NOT NULL`)
        await db.query(`ALTER TABLE "channel" ALTER COLUMN "is_excluded" DROP NOT NULL`)
        await db.query(`ALTER TABLE "channel" ALTER COLUMN "created_in_block" DROP NOT NULL`)
        await db.query(`ALTER TABLE "channel" ALTER COLUMN "reward_account" DROP NOT NULL`)
        await db.query(`ALTER TABLE "channel" ALTER COLUMN "channel_state_bloat_bond" DROP NOT NULL`)
        await db.query(`ALTER TABLE "channel" ALTER COLUMN "follows_num" DROP NOT NULL`)
        await db.query(`ALTER TABLE "channel" ALTER COLUMN "video_views_num" DROP NOT NULL`)
        await db.query(`ALTER TABLE "channel" ALTER COLUMN "total_videos_created" DROP NOT NULL`)
        await db.query(`ALTER TABLE "video_featured_in_category" ALTER COLUMN "id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "video_featured_in_category" DROP CONSTRAINT "PK_f84d38b5cdb7567ac04d6e9d209"`)
        await db.query(`ALTER TABLE "video_category" ALTER COLUMN "id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "video_category" DROP CONSTRAINT "PK_2a5c61f32e9636ee10821e9a58d"`)
        await db.query(`ALTER TABLE "video_category" ALTER COLUMN "is_supported" DROP NOT NULL`)
        await db.query(`ALTER TABLE "video_category" ALTER COLUMN "created_in_block" DROP NOT NULL`)
        await db.query(`ALTER TABLE "license" ALTER COLUMN "id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "license" DROP CONSTRAINT "PK_f168ac1ca5ba87286d03b2ef905"`)
        await db.query(`ALTER TABLE "video_subtitle" ALTER COLUMN "id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "video_subtitle" DROP CONSTRAINT "PK_2ac3e585fc608e673e7fbf94d8e"`)
        await db.query(`ALTER TABLE "video_subtitle" ALTER COLUMN "type" DROP NOT NULL`)
        await db.query(`ALTER TABLE "video_subtitle" ALTER COLUMN "mime_type" DROP NOT NULL`)
        await db.query(`ALTER TABLE "comment_reaction" ALTER COLUMN "id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "comment_reaction" DROP CONSTRAINT "PK_87f27d282c06eb61b1e0cde2d24"`)
        await db.query(`ALTER TABLE "comment_reaction" ALTER COLUMN "reaction_id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "comment" ALTER COLUMN "id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "comment" DROP CONSTRAINT "PK_0b0e4bbc8415ec426f87f3a88e2"`)
        await db.query(`ALTER TABLE "comment" ALTER COLUMN "created_at" DROP NOT NULL`)
        await db.query(`ALTER TABLE "comment" ALTER COLUMN "text" DROP NOT NULL`)
        await db.query(`ALTER TABLE "comment" ALTER COLUMN "status" DROP NOT NULL`)
        await db.query(`ALTER TABLE "comment" ALTER COLUMN "replies_count" DROP NOT NULL`)
        await db.query(`ALTER TABLE "comment" ALTER COLUMN "reactions_count" DROP NOT NULL`)
        await db.query(`ALTER TABLE "comment" ALTER COLUMN "reactions_and_replies_count" DROP NOT NULL`)
        await db.query(`ALTER TABLE "comment" ALTER COLUMN "is_edited" DROP NOT NULL`)
        await db.query(`ALTER TABLE "comment" ALTER COLUMN "is_excluded" DROP NOT NULL`)
        await db.query(`ALTER TABLE "video_reaction" ALTER COLUMN "id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "video_reaction" DROP CONSTRAINT "PK_504876585c394f4ab33665dd44b"`)
        await db.query(`ALTER TABLE "video_reaction" ALTER COLUMN "created_at" DROP NOT NULL`)
        await db.query(`ALTER TABLE "video_reaction" ALTER COLUMN "reaction" DROP NOT NULL`)
        await db.query(`ALTER TABLE "video" ALTER COLUMN "id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "video" DROP CONSTRAINT "PK_1a2f3856250765d72e7e1636c8e"`)
        await db.query(`ALTER TABLE "video" ALTER COLUMN "created_at" DROP NOT NULL`)
        await db.query(`ALTER TABLE "video" ALTER COLUMN "is_censored" DROP NOT NULL`)
        await db.query(`ALTER TABLE "video" ALTER COLUMN "is_excluded" DROP NOT NULL`)
        await db.query(`ALTER TABLE "video" ALTER COLUMN "video_state_bloat_bond" DROP NOT NULL`)
        await db.query(`ALTER TABLE "video" ALTER COLUMN "created_in_block" DROP NOT NULL`)
        await db.query(`ALTER TABLE "video" ALTER COLUMN "is_comment_section_enabled" DROP NOT NULL`)
        await db.query(`ALTER TABLE "video" ALTER COLUMN "comments_count" DROP NOT NULL`)
        await db.query(`ALTER TABLE "video" ALTER COLUMN "is_reaction_feature_enabled" DROP NOT NULL`)
        await db.query(`ALTER TABLE "video" ALTER COLUMN "reactions_count" DROP NOT NULL`)
        await db.query(`ALTER TABLE "video" ALTER COLUMN "views_num" DROP NOT NULL`)
        await db.query(`ALTER TABLE "video" ALTER COLUMN "video_relevance" DROP NOT NULL`)
        await db.query(`ALTER TABLE "owned_nft" ALTER COLUMN "id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "owned_nft" DROP CONSTRAINT "PK_5e0c289b350e863668fff44bb56"`)
        await db.query(`ALTER TABLE "owned_nft" ALTER COLUMN "created_at" DROP NOT NULL`)
        await db.query(`ALTER TABLE "owned_nft" ALTER COLUMN "video_id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "owned_nft" DROP CONSTRAINT "UQ_466896e39b9ec953f4f2545622d"`)
        await db.query(`ALTER TABLE "owned_nft" ALTER COLUMN "owner" DROP NOT NULL`)
        await db.query(`ALTER TABLE "owned_nft" ALTER COLUMN "is_featured" DROP NOT NULL`)
        await db.query(`ALTER TABLE "channel_follow" ALTER COLUMN "id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "channel_follow" DROP CONSTRAINT "PK_9410df2b9a316af3f0d216f9487"`)
        await db.query(`ALTER TABLE "channel_follow" ALTER COLUMN "channel_id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "channel_follow" ALTER COLUMN "timestamp" DROP NOT NULL`)
        await db.query(`ALTER TABLE "video_view_event" ALTER COLUMN "id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "video_view_event" DROP CONSTRAINT "PK_2efd85597a6a7a704fc4d0f7701"`)
        await db.query(`ALTER TABLE "video_view_event" ALTER COLUMN "video_id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "video_view_event" ALTER COLUMN "timestamp" DROP NOT NULL`)
        await db.query(`ALTER TABLE "report" ALTER COLUMN "id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "report" DROP CONSTRAINT "PK_99e4d0bea58cba73c57f935a546"`)
        await db.query(`ALTER TABLE "report" ALTER COLUMN "timestamp" DROP NOT NULL`)
        await db.query(`ALTER TABLE "report" ALTER COLUMN "rationale" DROP NOT NULL`)
        await db.query(`ALTER TABLE "nft_featuring_request" ALTER COLUMN "id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "nft_featuring_request" DROP CONSTRAINT "PK_d0b1ccb74336b30b9575387d328"`)
        await db.query(`ALTER TABLE "nft_featuring_request" ALTER COLUMN "nft_id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "nft_featuring_request" ALTER COLUMN "timestamp" DROP NOT NULL`)
        await db.query(`ALTER TABLE "nft_featuring_request" ALTER COLUMN "rationale" DROP NOT NULL`)
        await db.query(`ALTER TABLE "user" ALTER COLUMN "id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "user" DROP CONSTRAINT "PK_cace4a159ff9f2512dd42373760"`)
        await db.query(`ALTER TABLE "user" ALTER COLUMN "is_root" DROP NOT NULL`)
        await db.query(`ALTER TABLE "account" ALTER COLUMN "id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "account" DROP CONSTRAINT "PK_54115ee388cdb6d86bb4bf5b2ea"`)
        await db.query(`ALTER TABLE "account" ALTER COLUMN "user_id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "account" DROP CONSTRAINT "UQ_efef1e5fdbe318a379c06678c51"`)
        await db.query(`ALTER TABLE "account" ALTER COLUMN "email" DROP NOT NULL`)
        await db.query(`ALTER TABLE "account" DROP CONSTRAINT "UQ_4c8f96ccf523e9a3faefd5bdd4c"`)
        await db.query(`ALTER TABLE "account" ALTER COLUMN "is_email_confirmed" DROP NOT NULL`)
        await db.query(`ALTER TABLE "account" ALTER COLUMN "is_blocked" DROP NOT NULL`)
        await db.query(`ALTER TABLE "account" ALTER COLUMN "registered_at" DROP NOT NULL`)
        await db.query(`ALTER TABLE "account" ALTER COLUMN "membership_id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "account" DROP CONSTRAINT "UQ_601b93655bcbe73cb58d8c80cd3"`)
        await db.query(`ALTER TABLE "account" ALTER COLUMN "joystream_account" DROP NOT NULL`)
        await db.query(`ALTER TABLE "account" DROP CONSTRAINT "UQ_df4da05a7a80c1afd18b8f09900"`)
        await db.query(`ALTER TABLE "session" ALTER COLUMN "id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "session" DROP CONSTRAINT "PK_f55da76ac1c3ac420f444d2ff11"`)
        await db.query(`ALTER TABLE "session" ALTER COLUMN "browser" DROP NOT NULL`)
        await db.query(`ALTER TABLE "session" ALTER COLUMN "os" DROP NOT NULL`)
        await db.query(`ALTER TABLE "session" ALTER COLUMN "device" DROP NOT NULL`)
        await db.query(`ALTER TABLE "session" ALTER COLUMN "ip" DROP NOT NULL`)
        await db.query(`ALTER TABLE "session" ALTER COLUMN "started_at" DROP NOT NULL`)
        await db.query(`ALTER TABLE "session" ALTER COLUMN "expiry" DROP NOT NULL`)
        await db.query(`ALTER TABLE "token" ALTER COLUMN "id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "token" DROP CONSTRAINT "PK_82fae97f905930df5d62a702fc9"`)
        await db.query(`ALTER TABLE "token" ALTER COLUMN "type" DROP NOT NULL`)
        await db.query(`ALTER TABLE "token" ALTER COLUMN "issued_at" DROP NOT NULL`)
        await db.query(`ALTER TABLE "token" ALTER COLUMN "expiry" DROP NOT NULL`)
        await db.query(`ALTER TABLE "event" ALTER COLUMN "id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "event" DROP CONSTRAINT "PK_30c2f3bbaf6d34a55f8ae6e4614"`)
        await db.query(`ALTER TABLE "event" ALTER COLUMN "in_block" DROP NOT NULL`)
        await db.query(`ALTER TABLE "event" ALTER COLUMN "index_in_block" DROP NOT NULL`)
        await db.query(`ALTER TABLE "event" ALTER COLUMN "timestamp" DROP NOT NULL`)
        await db.query(`ALTER TABLE "event" ALTER COLUMN "data" DROP NOT NULL`)
        await db.query(`ALTER TABLE "notification" ALTER COLUMN "id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "notification" DROP CONSTRAINT "PK_705b6c7cdf9b2c2ff7ac7872cb7"`)
        await db.query(`ALTER TABLE "nft_history_entry" ALTER COLUMN "id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "nft_history_entry" DROP CONSTRAINT "PK_9018e80b335a965a54959c4c6e2"`)
        await db.query(`ALTER TABLE "nft_activity" ALTER COLUMN "id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "nft_activity" DROP CONSTRAINT "PK_1553b1bbf8000039875a6e31536"`)
        await db.query(`ALTER TABLE "gateway_config" ALTER COLUMN "id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "gateway_config" DROP CONSTRAINT "PK_db1fa5a857fb6292eee4c493e6f"`)
        await db.query(`ALTER TABLE "gateway_config" ALTER COLUMN "value" DROP NOT NULL`)
        await db.query(`ALTER TABLE "gateway_config" ALTER COLUMN "updated_at" DROP NOT NULL`)
        await db.query(`ALTER TABLE "video_hero" ALTER COLUMN "id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "video_hero" DROP CONSTRAINT "PK_f3b63979879773378afac0b9495"`)
        await db.query(`ALTER TABLE "video_hero" ALTER COLUMN "hero_title" DROP NOT NULL`)
        await db.query(`ALTER TABLE "video_hero" ALTER COLUMN "hero_video_cut_url" DROP NOT NULL`)
        await db.query(`ALTER TABLE "video_hero" ALTER COLUMN "hero_poster_url" DROP NOT NULL`)
        await db.query(`ALTER TABLE "video_media_encoding" ALTER COLUMN "id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "video_media_encoding" DROP CONSTRAINT "PK_52e25874f8d8a381e154d1125e0"`)
        await db.query(`ALTER TABLE "video_media_metadata" ALTER COLUMN "id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "video_media_metadata" DROP CONSTRAINT "PK_86a13815734e589cd86d0465e2d"`)
        await db.query(`ALTER TABLE "video_media_metadata" ALTER COLUMN "video_id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "video_media_metadata" DROP CONSTRAINT "UQ_4dc101240e8e1536b770aee202a"`)
        await db.query(`ALTER TABLE "video_media_metadata" ALTER COLUMN "created_in_block" DROP NOT NULL`)
        await db.query(`DROP INDEX "public"."IDX_9e594e5a61c0f3cb25679f6ba8"`)
        await db.query(`DROP INDEX "public"."IDX_3caf2d6b31d2fe45a2b85b8191"`)
        await db.query(`DROP INDEX "public"."IDX_e7618559409a903a897164156b"`)
        await db.query(`DROP INDEX "public"."IDX_32cb73025ec49c87f4c594a265"`)
        await db.query(`DROP INDEX "public"."IDX_cfb47e97e60c9d1462576f85a8"`)
        await db.query(`DROP INDEX "public"."IDX_a3127ec87cccc5696b92cac4e0"`)
        await db.query(`DROP INDEX "public"."IDX_1673ad4b059742fbabfc40b275"`)
        await db.query(`DROP INDEX "public"."IDX_ed36c6c26bf5410796c2fc21f7"`)
        await db.query(`DROP INDEX "public"."IDX_f29ff095bdb945975deca021ad"`)
        await db.query(`DROP INDEX "public"."IDX_ff8014300b8039dbaed764f51b"`)
        await db.query(`DROP INDEX "public"."IDX_25c85bc448b5e236a4c1a5f789"`)
        await db.query(`DROP INDEX "public"."IDX_a77e12f3d8c6ced020e179a5e9"`)
        await db.query(`DROP INDEX "public"."IDX_6997e94413b3f2f25a84e4a96f"`)
        await db.query(`DROP INDEX "public"."IDX_e58a2e1d78b8eccf40531a7fdb"`)
        await db.query(`DROP INDEX "public"."IDX_118ecfa0199aeb5a014906933e"`)
        await db.query(`DROP INDEX "public"."IDX_7b16ddad43901921a8d3c8eab7"`)
        await db.query(`DROP INDEX "public"."IDX_6d0917e1ac0cc06c8075bcf256"`)
        await db.query(`DROP INDEX "public"."IDX_cbe7e5d162a819e4ee2e2f6105"`)
        await db.query(`DROP INDEX "public"."IDX_da26b34f037c0d59d3c0d0646e"`)
        await db.query(`DROP INDEX "public"."IDX_2203674f18d8052ed6bac39625"`)
        await db.query(`DROP INDEX "public"."IDX_ffa63c28188eecc32af921bfc3"`)
        await db.query(`DROP INDEX "public"."IDX_b6eabfb8de4128b28d73681020"`)
        await db.query(`DROP INDEX "public"."IDX_15080d9fb7cf8b563103dd9d90"`)
        await db.query(`DROP INDEX "public"."IDX_962582f04d3f639e33f43c54bb"`)
        await db.query(`DROP INDEX "public"."IDX_d7995b1d57614a6fbd0c103874"`)
        await db.query(`DROP INDEX "public"."IDX_3ce66469b26697baa097f8da92"`)
        await db.query(`DROP INDEX "public"."IDX_1ff03403fd31dfeaba0623a89c"`)
        await db.query(`DROP INDEX "public"."IDX_c3c2abe750c76c7c8e305f71f2"`)
        await db.query(`DROP INDEX "public"."IDX_ac69bddf8202b7c0752d9dc8f3"`)
        await db.query(`DROP INDEX "public"."IDX_73dda64f53bbc7ec7035d5e7f0"`)
        await db.query(`DROP INDEX "public"."IDX_436a3836eb47acb5e1e3c88dde"`)
        await db.query(`DROP INDEX "public"."IDX_81b11ef99a9db9ef1aed040d75"`)
        await db.query(`DROP INDEX "public"."IDX_2a5c61f32e9636ee10821e9a58"`)
        await db.query(`DROP INDEX "public"."IDX_8530d052cc79b420f7ce2b4e09"`)
        await db.query(`DROP INDEX "public"."IDX_75fbab42a4cb18371b6d5004b0"`)
        await db.query(`DROP INDEX "public"."IDX_3ec633ae5d0477f512b4ed957d"`)
        await db.query(`DROP INDEX "public"."IDX_2db879ed42e3308fe65e679672"`)
        await db.query(`DROP INDEX "public"."IDX_54f88a7decf7d22fd9bd9fa439"`)
        await db.query(`DROP INDEX "public"."IDX_6c49ad08c44d36d11f77c426e4"`)
        await db.query(`DROP INDEX "public"."IDX_466896e39b9ec953f4f2545622"`)
        await db.query(`DROP INDEX "public"."IDX_822778b4b1ea8e3b60b127cb8b"`)
        await db.query(`DROP INDEX "public"."IDX_9bc0651dda94437ec18764a260"`)
        await db.query(`DROP INDEX "public"."IDX_2e29fba63e12a2b1818e0782d7"`)
        await db.query(`DROP INDEX "public"."IDX_31e1e798ec387ad905cf98d33b"`)
        await db.query(`DROP INDEX "public"."IDX_c6686efa4cd49fa9a429f01bac"`)
        await db.query(`DROP INDEX "public"."IDX_893057921f4b5cc37a0ef36684"`)
        await db.query(`DROP INDEX "public"."IDX_f732b6f82095a935db68c9491f"`)
        await db.query(`DROP INDEX "public"."IDX_519be2a41216c278c35f254dcb"`)
        await db.query(`DROP INDEX "public"."IDX_76d87e26cce72ac2e7ffa28dfb"`)
        await db.query(`DROP INDEX "public"."IDX_efef1e5fdbe318a379c06678c5"`)
        await db.query(`DROP INDEX "public"."IDX_4c8f96ccf523e9a3faefd5bdd4"`)
        await db.query(`DROP INDEX "public"."IDX_601b93655bcbe73cb58d8c80cd"`)
        await db.query(`DROP INDEX "public"."IDX_df4da05a7a80c1afd18b8f0990"`)
        await db.query(`DROP INDEX "public"."IDX_30e98e8746699fb9af235410af"`)
        await db.query(`DROP INDEX "public"."IDX_fae5a6b4a57f098e9af8520d49"`)
        await db.query(`DROP INDEX "public"."IDX_213b5a19bfdbe0ab6e06b1dede"`)
        await db.query(`DROP INDEX "public"."IDX_a6fe18c105f85a63d761ccb078"`)
        await db.query(`DROP INDEX "public"."IDX_8f3f220c4e717207d841d4e6d4"`)
        await db.query(`DROP INDEX "public"."IDX_ac8de39626657d3c0e909d9d82"`)
        await db.query(`DROP INDEX "public"."IDX_122be1f0696e0255acf95f9e33"`)
        await db.query(`DROP INDEX "public"."IDX_57f51d35ecab042478fe2e31c1"`)
        await db.query(`DROP INDEX "public"."IDX_d1a28b178f5d028d048d40ce20"`)
        await db.query(`DROP INDEX "public"."IDX_18a65713a9fd0715c7a980f5d5"`)
        await db.query(`DROP INDEX "public"."IDX_94d325a753f2c08fdd416eb095"`)
        await db.query(`DROP INDEX "public"."IDX_9feac5d9713a9f07e32eb8ba7a"`)
        await db.query(`DROP INDEX "public"."IDX_5944dc5896cb16bd395414a0ce"`)
        await db.query(`DROP INDEX "public"."IDX_4dc101240e8e1536b770aee202"`)
        await db.query(`ALTER TABLE "banned_member" DROP CONSTRAINT "BannedMember_member_channel"`)
        await db.query(`ALTER TABLE "video_featured_in_category" DROP CONSTRAINT "VideoFeaturedInCategory_category_video"`)
        await db.query(`ALTER TABLE "bid" DROP CONSTRAINT "FK_9e594e5a61c0f3cb25679f6ba8d"`)
        await db.query(`ALTER TABLE "bid" DROP CONSTRAINT "FK_3caf2d6b31d2fe45a2b85b81912"`)
        await db.query(`ALTER TABLE "bid" DROP CONSTRAINT "FK_e7618559409a903a897164156b7"`)
        await db.query(`ALTER TABLE "bid" DROP CONSTRAINT "FK_32cb73025ec49c87f4c594a265f"`)
        await db.query(`ALTER TABLE "auction" DROP CONSTRAINT "FK_cfb47e97e60c9d1462576f85a88"`)
        await db.query(`ALTER TABLE "auction" DROP CONSTRAINT "FK_a3127ec87cccc5696b92cac4e09"`)
        await db.query(`ALTER TABLE "auction" DROP CONSTRAINT "FK_1673ad4b059742fbabfc40b275c"`)
        await db.query(`ALTER TABLE "auction_whitelisted_member" DROP CONSTRAINT "FK_aad797677bc7c7c7dc1f1d397f5"`)
        await db.query(`ALTER TABLE "banned_member" DROP CONSTRAINT "FK_b94ea874da235d9b6fbc35cf58e"`)
        await db.query(`ALTER TABLE "banned_member" DROP CONSTRAINT "FK_ed36c6c26bf5410796c2fc21f74"`)
        await db.query(`ALTER TABLE "storage_data_object" DROP CONSTRAINT "FK_ff8014300b8039dbaed764f51bc"`)
        await db.query(`ALTER TABLE "channel" DROP CONSTRAINT "FK_25c85bc448b5e236a4c1a5f7895"`)
        await db.query(`ALTER TABLE "channel" DROP CONSTRAINT "FK_a77e12f3d8c6ced020e179a5e94"`)
        await db.query(`ALTER TABLE "channel" DROP CONSTRAINT "FK_6997e94413b3f2f25a84e4a96f8"`)
        await db.query(`ALTER TABLE "channel" DROP CONSTRAINT "FK_118ecfa0199aeb5a014906933e8"`)
        await db.query(`ALTER TABLE "video_featured_in_category" DROP CONSTRAINT "FK_7b16ddad43901921a8d3c8eab71"`)
        await db.query(`ALTER TABLE "video_featured_in_category" DROP CONSTRAINT "FK_0e6bb49ce9d022cd872f3ab4288"`)
        await db.query(`ALTER TABLE "video_category" DROP CONSTRAINT "FK_da26b34f037c0d59d3c0d0646e9"`)
        await db.query(`ALTER TABLE "video_subtitle" DROP CONSTRAINT "FK_2203674f18d8052ed6bac396252"`)
        await db.query(`ALTER TABLE "video_subtitle" DROP CONSTRAINT "FK_b6eabfb8de4128b28d73681020f"`)
        await db.query(`ALTER TABLE "comment_reaction" DROP CONSTRAINT "FK_15080d9fb7cf8b563103dd9d900"`)
        await db.query(`ALTER TABLE "comment_reaction" DROP CONSTRAINT "FK_962582f04d3f639e33f43c54bbc"`)
        await db.query(`ALTER TABLE "comment_reaction" DROP CONSTRAINT "FK_d7995b1d57614a6fbd0c103874d"`)
        await db.query(`ALTER TABLE "comment" DROP CONSTRAINT "FK_3ce66469b26697baa097f8da923"`)
        await db.query(`ALTER TABLE "comment" DROP CONSTRAINT "FK_1ff03403fd31dfeaba0623a89cf"`)
        await db.query(`ALTER TABLE "comment" DROP CONSTRAINT "FK_ac69bddf8202b7c0752d9dc8f32"`)
        await db.query(`ALTER TABLE "video_reaction" DROP CONSTRAINT "FK_73dda64f53bbc7ec7035d5e7f09"`)
        await db.query(`ALTER TABLE "video_reaction" DROP CONSTRAINT "FK_436a3836eb47acb5e1e3c88ddea"`)
        await db.query(`ALTER TABLE "video" DROP CONSTRAINT "FK_81b11ef99a9db9ef1aed040d750"`)
        await db.query(`ALTER TABLE "video" DROP CONSTRAINT "FK_2a5c61f32e9636ee10821e9a58d"`)
        await db.query(`ALTER TABLE "video" DROP CONSTRAINT "FK_8530d052cc79b420f7ce2b4e09d"`)
        await db.query(`ALTER TABLE "video" DROP CONSTRAINT "FK_3ec633ae5d0477f512b4ed957d6"`)
        await db.query(`ALTER TABLE "video" DROP CONSTRAINT "FK_2db879ed42e3308fe65e6796729"`)
        await db.query(`ALTER TABLE "video" DROP CONSTRAINT "FK_54f88a7decf7d22fd9bd9fa439a"`)
        await db.query(`ALTER TABLE "video" DROP CONSTRAINT "FK_6c49ad08c44d36d11f77c426e43"`)
        await db.query(`ALTER TABLE "owned_nft" DROP CONSTRAINT "FK_466896e39b9ec953f4f2545622d"`)
        await db.query(`ALTER TABLE "channel_follow" DROP CONSTRAINT "FK_822778b4b1ea8e3b60b127cb8b1"`)
        await db.query(`ALTER TABLE "video_view_event" DROP CONSTRAINT "FK_31e1e798ec387ad905cf98d33b0"`)
        await db.query(`ALTER TABLE "report" DROP CONSTRAINT "FK_c6686efa4cd49fa9a429f01bac8"`)
        await db.query(`ALTER TABLE "nft_featuring_request" DROP CONSTRAINT "FK_519be2a41216c278c35f254dcba"`)
        await db.query(`ALTER TABLE "account" DROP CONSTRAINT "FK_efef1e5fdbe318a379c06678c51"`)
        await db.query(`ALTER TABLE "account" DROP CONSTRAINT "FK_601b93655bcbe73cb58d8c80cd3"`)
        await db.query(`ALTER TABLE "encryption_artifacts" DROP CONSTRAINT "FK_ec8f68a544aadc4fbdadefe4a0a"`)
        await db.query(`ALTER TABLE "session" DROP CONSTRAINT "FK_30e98e8746699fb9af235410aff"`)
        await db.query(`ALTER TABLE "session" DROP CONSTRAINT "FK_fae5a6b4a57f098e9af8520d499"`)
        await db.query(`ALTER TABLE "session_encryption_artifacts" DROP CONSTRAINT "FK_3612880efd8926a17eba5ab0e1a"`)
        await db.query(`ALTER TABLE "token" DROP CONSTRAINT "FK_a6fe18c105f85a63d761ccb0780"`)
        await db.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_ac8de39626657d3c0e909d9d82f"`)
        await db.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_122be1f0696e0255acf95f9e336"`)
        await db.query(`ALTER TABLE "nft_history_entry" DROP CONSTRAINT "FK_57f51d35ecab042478fe2e31c19"`)
        await db.query(`ALTER TABLE "nft_history_entry" DROP CONSTRAINT "FK_d1a28b178f5d028d048d40ce208"`)
        await db.query(`ALTER TABLE "nft_activity" DROP CONSTRAINT "FK_18a65713a9fd0715c7a980f5d54"`)
        await db.query(`ALTER TABLE "nft_activity" DROP CONSTRAINT "FK_94d325a753f2c08fdd416eb095f"`)
        await db.query(`ALTER TABLE "video_hero" DROP CONSTRAINT "FK_9feac5d9713a9f07e32eb8ba7a1"`)
        await db.query(`ALTER TABLE "video_media_metadata" DROP CONSTRAINT "FK_5944dc5896cb16bd395414a0ce0"`)
        await db.query(`ALTER TABLE "video_media_metadata" DROP CONSTRAINT "FK_4dc101240e8e1536b770aee202a"`)
    }
}
