version: '3.3'
services:
  orion:
    image: joystream/orion:latest
    environment:
      - ORION_PORT=6116
      - ORION_MONGO_HOSTNAME=mongo
      - ORION_FEATURED_CONTENT_SECRET=change_me_please
      - ORION_ADMIN_SECRET=change_me_please
      - ORION_QUERY_NODE_URL=https://query.joystream.org/graphql
    ports:
      - '127.0.0.1:6116:6116'
    restart: always
  mongo:
    restart: always
    image: library/mongo:4.4
    volumes:
      - ./db:/data/db
