version: '3'

services:
  processor_db:
    container_name: subsquid_db
    image: postgres:14
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: squid
    ports:
      - '${DB_PORT}:5432'
    command: ['postgres', '-c', 'log_statement=all']
    shm_size: 1g
#    volumes:
#      - ./data/db:/var/lib/postgresql/data

