services:
  orion_db:
    container_name: orion_db
    hostname: orion_db
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: squid
    logging:
      driver: 'local'
      options:
        max-size: '200m'
        max-file: '10'
    networks:
      - joystream_default
    ports:
      - '127.0.0.1:${DB_PORT}:${DB_PORT}'
      - '[::1]:${DB_PORT}:${DB_PORT}'
    command: ['postgres', '-c', 'config_file=/etc/postgresql/postgresql.conf', '-p', '${DB_PORT}']
    shm_size: 1g
    volumes:
      - orion_db_data:/var/lib/postgresql/data
      - ./db/postgres.conf:/etc/postgresql/postgresql.conf

  orion_processor:
    container_name: orion_processor
    hostname: orion_processor
    image: node:18
    restart: unless-stopped
    networks:
      - joystream_default
    env_file:
      - .env
      - docker.env
    environment:
      - TYPEORM_SUBSCRIBERS_DIR=lib/mappings/subscribers
    ports:
      - '127.0.0.1:${PROCESSOR_PROMETHEUS_PORT}:${PROCESSOR_PROMETHEUS_PORT}'
      - '[::1]:${PROCESSOR_PROMETHEUS_PORT}:${PROCESSOR_PROMETHEUS_PORT}'
    depends_on:
      - orion_db
    volumes:
      - type: bind
        source: .
        target: /orion
    working_dir: /orion
    command: ['make', 'process']

  orion_relevance-service:
    container_name: orion_relevance-service
    image: node:18
    restart: unless-stopped
    networks:
      - joystream_default
    depends_on:
      - orion_rabbitmq
    env_file:
      - .env
      - docker.env
    volumes:
      - type: bind
        source: .
        target: /orion
    working_dir: /orion
    command: ['make', 'relevance-service']

  orion_rabbitmq:
    container_name: orion_rabbitmq
    hostname: orion_rabbitmq
    image: rabbitmq:4.1
    networks:
      - joystream_default
    ports:
      - '127.0.0.1:${RABBITMQ_PORT}:${RABBITMQ_PORT}'
      - '[::1]:${RABBITMQ_PORT}:${RABBITMQ_PORT}'

  orion_graphql-server:
    container_name: orion_graphql-server
    hostname: orion_graphql-server
    image: node:18
    restart: unless-stopped
    networks:
      - joystream_default
    env_file:
      - .env
      - docker.env
    environment:
      - SQD_TRACE=authentication
      - OTEL_EXPORTER_OTLP_ENDPOINT=${TELEMETRY_ENDPOINT}
      - TYPEORM_SUBSCRIBERS_DIR=lib/server-extension/subscribers
    depends_on:
      - orion_db
    volumes:
      - type: bind
        source: .
        target: /orion
    working_dir: /orion
    command: ['make', 'serve']
    ports:
      - '4350:4350'

  orion_auth-api:
    container_name: orion_auth-api
    hostname: orion_auth-api
    image: node:18
    restart: unless-stopped
    networks:
      - joystream_default
    env_file:
      - .env
      - docker.env
    environment:
      - SQD_TRACE=authentication
      - OTEL_EXPORTER_OTLP_ENDPOINT=${TELEMETRY_ENDPOINT}
    depends_on:
      - orion_db
    volumes:
      - type: bind
        source: .
        target: /orion
    working_dir: /orion
    command: ['make', 'serve-auth-api']
    ports:
      - '${AUTH_API_PORT}:${AUTH_API_PORT}'

volumes:
  orion_db_data:

networks:
  joystream_default:
    external: true
