version: '3'

services:
  db:
    container_name: orion_db
    hostname: orion_db
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: squid
    ports:
      - '127.0.0.1:${DB_PORT}:5432'
      - '[::1]:${DB_PORT}:5432'
    command: ['postgres', '-c', 'log_statement=all']
    shm_size: 1g
    volumes:
      - orion_db_data:/var/lib/postgresql/data

  processor:
    container_name: orion_processor
    hostname: orion_processor
    image: node:14
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DB_HOST=orion_db
      - DB_PORT=5432
      - ARCHIVE_GATEWAY_HOST=orion_archive_gateway
      - ARCHIVE_GATEWAY_PORT=8000
    ports:
      - '127.0.0.1:${PROCESSOR_PROMETHEUS_PORT}:${PROCESSOR_PROMETHEUS_PORT}'
      - '[::1]:${PROCESSOR_PROMETHEUS_PORT}:${PROCESSOR_PROMETHEUS_PORT}'
    depends_on:
      - db
    volumes:
      - type: bind
        source: .
        target: /orion
    working_dir: /orion
    command: ['make', 'process']

  graphql-server:
    container_name: orion_graphql-server
    hostname: orion_graphql-server
    image: node:14
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PROCESSOR_HOST=orion_processor
      - DB_HOST=orion_db
      - DB_PORT=5432
    depends_on:
      - db
    volumes:
      - type: bind
        source: .
        target: /orion
    working_dir: /orion
    command: ['make', 'serve']
    ports:
      - '4350:4350'

volumes:
  orion_db_data:

networks:
  default:
    external:
      name: joystream_default
