version: '3'

services:
  orion_db:
    container_name: orion_db
    hostname: orion_db
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: squid
    ports:
      - '127.0.0.1:${DB_PORT}:${DB_PORT}'
      - '[::1]:${DB_PORT}:${DB_PORT}'
    command: ['postgres', '-c', 'config_file=/etc/postgresql/postgresql.conf', '-p', '${DB_PORT}']
    shm_size: 1g
    volumes:
      - orion_db_data:/var/lib/postgresql/data
      - ./db/postgres.conf:/etc/postgresql/postgresql.conf

  interactions_db:
    image: mongo:7.0.0
    container_name: interactions_db
    hostname: interactions_db
    profiles: ['interactions']
    restart: unless-stopped
    shm_size: 1g
    command: ['mongod', '--port', '${INTERACTIONS_DB_PORT}']
    ports:
      - '${INTERACTIONS_DB_PORT}:${INTERACTIONS_DB_PORT}'
    volumes:
      - interactions_db_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: squid
      MONGO_INITDB_ROOT_PASSWORD: squid

  orion_processor:
    container_name: orion_processor
    hostname: orion_processor
    image: node:18
    restart: unless-stopped
    env_file:
      - .env
      - docker.env
    ports:
      - '127.0.0.1:${PROCESSOR_PROMETHEUS_PORT}:${PROCESSOR_PROMETHEUS_PORT}'
      - '[::1]:${PROCESSOR_PROMETHEUS_PORT}:${PROCESSOR_PROMETHEUS_PORT}'
    depends_on:
      - orion_db
    volumes:
      - processor_queue:/app/persistedQueue
      - type: bind
        source: .
        target: /orion
    working_dir: /orion
    command: ['make', 'process']

  orion_graphql-server:
    container_name: orion_graphql-server
    hostname: orion_graphql-server
    image: node:18
    restart: unless-stopped
    env_file:
      - .env
      - docker.env
    environment:
      - SQD_TRACE=authentication
      - OTEL_EXPORTER_OTLP_ENDPOINT=${TELEMETRY_ENDPOINT}
    depends_on:
      - orion_db
    volumes:
      - graphql_queue:/app/persistedQueue
      - type: bind
        source: .
        target: /orion
    working_dir: /orion
    command: ['make', 'serve']
    ports:
      - '4350:4350'

  orion_auth-api:
    container_name: orion_auth-api
    hostname: orion_auth-api
    image: node:18
    restart: unless-stopped
    env_file:
      - .env
      - docker.env
    environment:
      - SQD_TRACE=authentication
      - OTEL_EXPORTER_OTLP_ENDPOINT=${TELEMETRY_ENDPOINT}
    depends_on:
      - orion_db
    volumes:
      - auth_api_queue:/app/persistedQueue
      - type: bind
        source: .
        target: /orion
    working_dir: /orion
    command: ['make', 'serve-auth-api']
    ports:
      - '${AUTH_API_PORT}:${AUTH_API_PORT}'

  orion_interactions-api:
    container_name: orion_interactions-api
    hostname: orion_interactions-api
    profiles: ['interactions']
    image: node:18
    restart: unless-stopped
    env_file:
      - .env
      - docker.env
    environment:
      - SQD_TRACE=interactions
    depends_on:
      - orion_db
    volumes:
      - interactions_api_queue:/app/persistedQueue
      - type: bind
        source: .
        target: /orion
    working_dir: /orion
    command: ['make', 'serve-interactions-api']
    ports:
      - '${INTERACTIONS_API_PORT}:${INTERACTIONS_API_PORT}'

volumes:
  orion_db_data:
  interactions_db_data:
  interactions_api_queue:
  auth_api_queue:
  graphql_queue:
  processor_queue:

networks:
  default:
    external:
      name: joystream_default
