version: '3'

services:
  orion_db:
    container_name: orion_db
    hostname: orion_db
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: squid
    ports:
      - '127.0.0.1:${DB_PORT}:${DB_PORT}'
      - '[::1]:${DB_PORT}:${DB_PORT}'
    command: ['postgres', '-c', 'config_file=/etc/postgresql/postgresql.conf', '-p', '${DB_PORT}']
    shm_size: 1g
    volumes:
      - orion_db_data:/var/lib/postgresql/data
      - ./db/postgres.conf:/etc/postgresql/postgresql.conf

  orion_processor:
    container_name: orion_processor
    hostname: orion_processor
    image: node:18
    restart: unless-stopped
    env_file:
      - .env
      - docker.env
    ports:
      - '127.0.0.1:${PROCESSOR_PROMETHEUS_PORT}:${PROCESSOR_PROMETHEUS_PORT}'
      - '[::1]:${PROCESSOR_PROMETHEUS_PORT}:${PROCESSOR_PROMETHEUS_PORT}'
    depends_on:
      - orion_db
    volumes:
      - type: bind
        source: .
        target: /orion
    working_dir: /orion
    command: ['make', 'process']

  orion_graphql-server:
    container_name: orion_graphql-server
    hostname: orion_graphql-server
    image: node:18
    restart: unless-stopped
    env_file:
      - .env
      - docker.env
    environment:
      - SQD_TRACE=authentication
      - OTEL_EXPORTER_OTLP_ENDPOINT=${TELEMETRY_ENDPOINT}
    depends_on:
      - orion_db
    volumes:
      - type: bind
        source: .
        target: /orion
    working_dir: /orion
    command: ['make', 'serve']
    ports:
      - '4350:4350'

  orion_auth-api:
    container_name: orion_auth-api
    hostname: orion_auth-api
    image: node:18
    restart: unless-stopped
    env_file:
      - .env
      - docker.env
    environment:
      - SQD_TRACE=authentication
      - OTEL_EXPORTER_OTLP_ENDPOINT=${TELEMETRY_ENDPOINT}
    depends_on:
      - orion_db
    volumes:
      - type: bind
        source: .
        target: /orion
    working_dir: /orion
    command: ['make', 'serve-auth-api']
    ports:
      - '${AUTH_API_PORT}:${AUTH_API_PORT}'

volumes:
  orion_db_data:

networks:
  default:
    external:
      name: joystream_default
