"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AccountResolver = exports.NftResolver = exports.AssetsResolver = exports.VideosResolver = exports.StateResolver = exports.VideoCategoriesResolver = exports.ChannelsResolver = exports.AdminResolver = void 0;
var AdminResolver_1 = require("./resolvers/AdminResolver");
Object.defineProperty(exports, "AdminResolver", { enumerable: true, get: function () { return AdminResolver_1.AdminResolver; } });
var ChannelsResolver_1 = require("./resolvers/ChannelsResolver");
Object.defineProperty(exports, "ChannelsResolver", { enumerable: true, get: function () { return ChannelsResolver_1.ChannelsResolver; } });
var VideoCategoriesResolver_1 = require("./resolvers/VideoCategoriesResolver");
Object.defineProperty(exports, "VideoCategoriesResolver", { enumerable: true, get: function () { return VideoCategoriesResolver_1.VideoCategoriesResolver; } });
var StateResolver_1 = require("./resolvers/StateResolver");
Object.defineProperty(exports, "StateResolver", { enumerable: true, get: function () { return StateResolver_1.StateResolver; } });
var VideosResolver_1 = require("./resolvers/VideosResolver");
Object.defineProperty(exports, "VideosResolver", { enumerable: true, get: function () { return VideosResolver_1.VideosResolver; } });
var AssetsResolver_1 = require("./resolvers/AssetsResolver");
Object.defineProperty(exports, "AssetsResolver", { enumerable: true, get: function () { return AssetsResolver_1.AssetsResolver; } });
var NftResolver_1 = require("./resolvers/NftResolver");
Object.defineProperty(exports, "NftResolver", { enumerable: true, get: function () { return NftResolver_1.NftResolver; } });
var AccountResolver_1 = require("./resolvers/AccountResolver");
Object.defineProperty(exports, "AccountResolver", { enumerable: true, get: function () { return AccountResolver_1.AccountResolver; } });
//# sourceMappingURL=resolvers.js.map