name: Build and save docker image

on: [push, pull_request]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: make build-docker
      - name: Save Docker image
        run: docker save joystream/orion:latest | gzip > orion-${{ github.sha }}.tar.gz
      - name: Upload Docker image
        uses: actions/upload-artifact@v3
        with:
          name: joystream-orion-docker
          path: orion-${{ github.sha }}.tar.gz
