name: Build & Publish Orion Docker image

on:
  workflow_dispatch:

jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Extract Package Version
        id: extract_version
        shell: bash
        run: |
          echo "orion_version=$(cat package.json | jq -r '.version')" >> $GITHUB_OUTPUT

      - name: Make some space
        shell: bash
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        if: github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build orion
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: false
          load: true
          tags: joystream/orion:latest

      - name: Push Orion Image
        run: |
          docker image tag joystream/orion:latest joystream/orion:${{ steps.extract_version.outputs.orion_version }}
          docker push joystream/orion:${{ steps.extract_version.outputs.orion_version }}

      - name: Push Orion latest tag
        if: github.ref == 'refs/heads/master'
        run: |
          docker push joystream/orion:latest
