name: Tests
on: [push, pull_request]

jobs:
  auth-api:
    name: Auth API tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: Prepare workspace
        run: make prepare
      - name: Run tests
        run: npm run tests:auth-api
