name: External integration tests

on:
  push:

jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: make build-docker
      - name: Save Docker image
        run: docker save joystream/orion:latest | gzip > orion-${{ github.sha }}.tar.gz
      - name: Upload Docker image
        uses: actions/upload-artifact@v3
        with:
          name: joystream-orion-docker
          path: orion-${{ github.sha }}.tar.gz
      - name: Trigger tests
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.TRIGGER_TESTS_TOKEN }}
          repo: Lezek123/substrate-runtime-joystream
          ref: orion-integration-tests
          workflow: run-network-tests.yml
          inputs: >
            {
              "orion_sha": "${{ github.sha }}"
            }
      - name: Set pending status
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{ github.repository }}/statuses/${{ github.sha }}
          state: pending
          description: Integration tests result
          context: integration-tests
