name: Trigger external integration tests

on: [push, pull_request_target]

jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    steps:
      - name: Wait until build-docker-image workflow finishes successfully
        run: |
          CONCLUSION="null"
          while [[ "$CONCLUSION" == "null" ]]
          do
            CONCLUSION=$(
              curl -L \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/${{ github.repository }}/actions/workflows/build-docker-image.yml/runs?head_sha=${{ github.sha }} \
                | jq -r '.workflow_runs[0].conclusion'
            )
            echo "build-docker-image workflow conclusion: $CONCLUSION"
            if [[ "$CONCLUSION" == "null" ]]
            then
              echo "Waiting for build-docker-image workflow to finish..."
              exit 1
            fi
          done
          if [[ "$CONCLUSION" != "success" ]]
          then
            echo "build-docker-image workflow failed"
            exit 1
          fi
      - name: Trigger tests
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.TRIGGER_TESTS_TOKEN }}
          repo: ${{ vars.INTEGRATION_TESTS_REPO }}
          ref: ${{ vars.INTEGRATION_TESTS_BRANCH }}
          workflow: run-network-tests.yml
          inputs: >
            {
              "orion_sha": "${{ github.sha }}"
            }
      - name: Set pending status
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{ github.repository }}/statuses/${{ github.sha }}
          state: pending
          description: Integration tests result
          context: integration-tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
